repos:
  - repo: local
    hooks:
      - id: brew-style-formula
        name: brew style formulae
        entry: ./scripts/brew-style-formula.sh
        language: system
        files: ^Formula/.*\.rb$
        pass_filenames: true
      - id: validate-workflows
        name: validate workflows
        entry: python3 scripts/check_workflow_checkout.py
        language: system
        files: ^\.github/workflows/.*\.ya?ml$
        pass_filenames: true
